name: Price Scraper

on:
  schedule:
    - cron: '0 */8 * * *'  # Cada 8 horas
  workflow_dispatch:  # Botón manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install puppeteer
      - run: node scraper.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: results.json
